### ISSUE TITLE
시연용 더미데이터 추가 필요

### ISSUE THREAD

**Issue by lkaybob** [capstone-jicos/Ongi-server#10]
현재는 지금 무의미한 데이터들(event1, detailAddress 등)만 채워져있는데, 중간 점검을 위해선 **실제로 사용하는 것 같은** 데이터들을 채워넣어야함. 이는 백엔드 측에서 해주는 것을 권장. 단 아래의 조건들을 만족시켜야함

1. 각 이미지 Path들은 모두 S3에 실제로 올라가있는 이미지 주소로 할 것. (의미없이 images1.jpg 이런 식으로 하면 Vue 엔진에서 404 에러나서 프론트 뷰가 올 스탑됨. 반드시 샘플 이미지를 S3에 올려놓고 그 이미지 Path를 쓸 것)
2. 지역에 대한 것들은 우선 모두 한글로 할 것. 별도의 테이블을 만들어서 Code Coversion할 공수가 없음.
3. 사용자 이름들도 적어도 실명에 가깝게 할 것 (못해도 김철수, 이영희 이 정도라도...)

Due Date : 화요일 자정 전까지 (화요일에서 수요일 넘어가는 자정 전까지, 그래야 목요일 발표 전 데모 동영상 찍을 수 있고, 미리 준비할 수 있음)

**Comment by Sjisoo** [comment]
추가 했습니다!
