### ISSUE TITLE
장소 제공 목록 조회 질문!

### ISSUE THREAD

**Issue by psmini** [capstone-jicos/Ongi-server#16]
프론트에서 
![image](https://user-images.githubusercontent.com/33715953/48824553-f7f2b580-eda7-11e8-9147-4157303b5f42.png)

위 형식으로 보내달라고 요청했었는데,
1. 첫번째 name은 Venue의 설정된 name이고, 두번째 name은 따로 디비에서 관리안하는것 같은데 어떻게 해야할까?
2. 필요사항/제약사항 또한 디비에서 관리안하고, Rules 라는 항목으로 추가된것 같은데 어떻게...?

일단 항목에 있는대로 
![image](https://user-images.githubusercontent.com/33715953/48824720-81a28300-eda8-11e8-98e6-538e9459c367.png)
임의로 이런식으로 처리했음

**Comment by lkaybob** [comment]
저게 정확히 어떤 API에 대한 스펙을 요청한거였지?? 기억이 지금 안 나서...

**Comment by psmini** [comment]
아 오키! 저렇게 4개 항목만 보내주는거로 수정할게~

**Comment by psmini** [comment]
`api.get('/me/venue', sessionChecker(), (req,res) => {   

        var venueListJson = {};
        var venueListArr = [];
        
        venueModel.findAll({
            where: {
                uniqueId: req.user.uniqueId
            }
        })
        .then(venueList => {

            for (var i=0; i<venueList.length; i++){
                venueListJson = {                        
                    "venueId":venueList[i]['idx'],
                    "name": venueList[i]['name'],
                    "address": venueList[i]['state'] +" "+ venueList[i]['city']+" "+ venueList[i]['detail'],
                    "photoUrl":venueList[i]['photoUrl']
                }
                venueListArr[i] = venueListJson;
            }
            res.send(venueListArr);
        })
    });`

![image](https://user-images.githubusercontent.com/33715953/48825688-83217a80-edab-11e8-8b0a-f41007eca77b.png)


우선 이렇게 처리했고, 추가로 사진 Url은 임의로 저렇게 적어둔건가?? 아니면 업로드쪽에서 저런식으로 저장하도록 수정이 필요한부분이야? 이게 마지막 질문일듯!

**Comment by lkaybob** [comment]
URL은 우선 임의로 적어둔거고, 실제 장소 등록할 때는 Upload API로 보내서 Photo URL을 받고, 실제 등록은 그 URL을 커밋해서 올려주는 형식으로 하려고. (이미 장소 등록 API에는 Photo URL 등록하는 것이 포함되어 있으니까)
